package com.aem.genericutilities;

public enum Exceptions {
	NULL_URL_EXCEPTION,
	INVALID_URL_EXCEPTION,
	NULL_WEBDRIVER_EXCEPTION,
	SOURCE_DESTINATION_VALUES_NULL_EXCEPTION,
	INVALID_LOCATOR_TYPE_EXCEPTION,
	LOCATOR_VALUE_NULL_EXCEPTION,
	COULD_NOT_LOCATE_ELEMENT_EXCEPTION
	
	}
